//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel.Connectors.Hotel.ErrorMapping.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class USGErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal USGErrors() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Travel.Connectors.Hotel.ErrorMapping.Resources.USGErrors", typeof(USGErrors).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid sessionId provided in the request..
        /// </summary>
        public static string ErrorCode1 {
            get {
                return ResourceManager.GetString("ErrorCode1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid culture provided in the header..
        /// </summary>
        public static string ErrorCode117 {
            get {
                return ResourceManager.GetString("ErrorCode117", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The following supplier exception occurred: {string|supplier}. This exception does not map with any existing supplier error..
        /// </summary>
        public static string ErrorCode12 {
            get {
                return ResourceManager.GetString("ErrorCode12", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to You cannot book more than {0} guests per room..
        /// </summary>
        public static string ErrorCode129 {
            get {
                return ResourceManager.GetString("ErrorCode129", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to There are no results for the search criteria provided..
        /// </summary>
        public static string ErrorCode13 {
            get {
                return ResourceManager.GetString("ErrorCode13", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The supplier does not support the {string|culture} culture..
        /// </summary>
        public static string ErrorCode131 {
            get {
                return ResourceManager.GetString("ErrorCode131", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The guest information is required for each room in the request..
        /// </summary>
        public static string ErrorCode133 {
            get {
                return ResourceManager.GetString("ErrorCode133", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The supplier server is unreachable. Try again after some time..
        /// </summary>
        public static string ErrorCode14 {
            get {
                return ResourceManager.GetString("ErrorCode14", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to An error occurred at the supplier&apos;s side. Try again after some time..
        /// </summary>
        public static string ErrorCode15 {
            get {
                return ResourceManager.GetString("ErrorCode15", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The supplier details are required in the request..
        /// </summary>
        public static string ErrorCode18 {
            get {
                return ResourceManager.GetString("ErrorCode18", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The supplierId field is required in the request..
        /// </summary>
        public static string ErrorCode19 {
            get {
                return ResourceManager.GetString("ErrorCode19", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid tenantId provided in the header..
        /// </summary>
        public static string ErrorCode2 {
            get {
                return ResourceManager.GetString("ErrorCode2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The supplierName field is required in the request..
        /// </summary>
        public static string ErrorCode20 {
            get {
                return ResourceManager.GetString("ErrorCode20", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Unable to find the supplier configuration..
        /// </summary>
        public static string ErrorCode21 {
            get {
                return ResourceManager.GetString("ErrorCode21", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The following supplier configuration details are required in the request: {0}, {1}..
        /// </summary>
        public static string ErrorCode22 {
            get {
                return ResourceManager.GetString("ErrorCode22", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The check-in date can only be up to a day prior to the current date..
        /// </summary>
        public static string ErrorCode23 {
            get {
                return ResourceManager.GetString("ErrorCode23", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The check-out date must be later than the check-in date..
        /// </summary>
        public static string ErrorCode24 {
            get {
                return ResourceManager.GetString("ErrorCode24", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The hotelId field is required in the request..
        /// </summary>
        public static string ErrorCode249 {
            get {
                return ResourceManager.GetString("ErrorCode249", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The check-out date cannot be earlier than the check-in date..
        /// </summary>
        public static string ErrorCode25 {
            get {
                return ResourceManager.GetString("ErrorCode25", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The tenantId field is required in the request..
        /// </summary>
        public static string ErrorCode251 {
            get {
                return ResourceManager.GetString("ErrorCode251", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Multiple hotel search criteria provided in the request. You can search for hotels by providing either the hotelId or the region..
        /// </summary>
        public static string ErrorCode26 {
            get {
                return ResourceManager.GetString("ErrorCode26", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The occupancy details are required in the request..
        /// </summary>
        public static string ErrorCode27 {
            get {
                return ResourceManager.GetString("ErrorCode27", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The request exceeded the maximum number of rooms that can be booked in a single request. You can book up to {0} rooms in a single request..
        /// </summary>
        public static string ErrorCode29 {
            get {
                return ResourceManager.GetString("ErrorCode29", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid currency provided in the request..
        /// </summary>
        public static string ErrorCode3 {
            get {
                return ResourceManager.GetString("ErrorCode3", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The request exceeded the maximum number of guests that can occupy a single room. A single room can have up to {0} guests..
        /// </summary>
        public static string ErrorCode30 {
            get {
                return ResourceManager.GetString("ErrorCode30", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to There must be at least one adult guest type per room..
        /// </summary>
        public static string ErrorCode31 {
            get {
                return ResourceManager.GetString("ErrorCode31", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to A timeout exception occurred..
        /// </summary>
        public static string ErrorCode32 {
            get {
                return ResourceManager.GetString("ErrorCode32", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to You cannot search for more than {0} rooms in a single call..
        /// </summary>
        public static string ErrorCode325 {
            get {
                return ResourceManager.GetString("ErrorCode325", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The stay duration must be at least 1 day..
        /// </summary>
        public static string ErrorCode326 {
            get {
                return ResourceManager.GetString("ErrorCode326", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Criteria is required in the request..
        /// </summary>
        public static string ErrorCode327 {
            get {
                return ResourceManager.GetString("ErrorCode327", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to A supplier exception occurred..
        /// </summary>
        public static string ErrorCode33 {
            get {
                return ResourceManager.GetString("ErrorCode33", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to An application exception occurred..
        /// </summary>
        public static string ErrorCode34 {
            get {
                return ResourceManager.GetString("ErrorCode34", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The stay duration cannot be more than {0} nights..
        /// </summary>
        public static string ErrorCode35 {
            get {
                return ResourceManager.GetString("ErrorCode35", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Content not found from the following suppliers: {List|supplierFamily}..
        /// </summary>
        public static string ErrorCode37 {
            get {
                return ResourceManager.GetString("ErrorCode37", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Connector metadata not found for the following suppliers: {List|supplier}..
        /// </summary>
        public static string ErrorCode38 {
            get {
                return ResourceManager.GetString("ErrorCode38", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid credentials provided in the supplier request..
        /// </summary>
        public static string ErrorCode41 {
            get {
                return ResourceManager.GetString("ErrorCode41", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The child age must be between {0} and {1}..
        /// </summary>
        public static string ErrorCode43 {
            get {
                return ResourceManager.GetString("ErrorCode43", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid search pattern details, either HotelIds, city or radial region should be present in criteria.
        /// </summary>
        public static string ErrorCode447 {
            get {
                return ResourceManager.GetString("ErrorCode447", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to You cannot book more than {0} guests..
        /// </summary>
        public static string ErrorCode470 {
            get {
                return ResourceManager.GetString("ErrorCode470", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The {0} is required in the request..
        /// </summary>
        public static string ErrorCode471 {
            get {
                return ResourceManager.GetString("ErrorCode471", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid hotel ids in request.
        /// </summary>
        public static string ErrorCode479 {
            get {
                return ResourceManager.GetString("ErrorCode479", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid correlation Id provided in the header..
        /// </summary>
        public static string ErrorCode497 {
            get {
                return ResourceManager.GetString("ErrorCode497", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid request. Verify the request format and then try again..
        /// </summary>
        public static string ErrorCode5 {
            get {
                return ResourceManager.GetString("ErrorCode5", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The following message headers are required: {0}..
        /// </summary>
        public static string ErrorCode51 {
            get {
                return ResourceManager.GetString("ErrorCode51", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to An error occurred while processing the request..
        /// </summary>
        public static string ErrorCode52 {
            get {
                return ResourceManager.GetString("ErrorCode52", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to An error occurred while using the result store..
        /// </summary>
        public static string ErrorCode53 {
            get {
                return ResourceManager.GetString("ErrorCode53", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to An error occurred while using the session store..
        /// </summary>
        public static string ErrorCode54 {
            get {
                return ResourceManager.GetString("ErrorCode54", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The following validation errors occurred: .
        /// </summary>
        public static string ErrorCode55 {
            get {
                return ResourceManager.GetString("ErrorCode55", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to MetadataRefreshSettings missing..
        /// </summary>
        public static string ErrorCode581 {
            get {
                return ResourceManager.GetString("ErrorCode581", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to A system error occurred. Try again after some time..
        /// </summary>
        public static string ErrorCode6 {
            get {
                return ResourceManager.GetString("ErrorCode6", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Unable to process the request due to a supplier side failure..
        /// </summary>
        public static string ErrorCode620 {
            get {
                return ResourceManager.GetString("ErrorCode620", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to An internal server error occured..
        /// </summary>
        public static string ErrorCode621 {
            get {
                return ResourceManager.GetString("ErrorCode621", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Each room must have at least one occupant..
        /// </summary>
        public static string ErrorCode64 {
            get {
                return ResourceManager.GetString("ErrorCode64", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The stay period is required in the request..
        /// </summary>
        public static string ErrorCode65 {
            get {
                return ResourceManager.GetString("ErrorCode65", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to An error occurred while using the metadata..
        /// </summary>
        public static string ErrorCode69 {
            get {
                return ResourceManager.GetString("ErrorCode69", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to No request found. You must provide a valid request..
        /// </summary>
        public static string ErrorCode7 {
            get {
                return ResourceManager.GetString("ErrorCode7", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Unable to parse supplier response..
        /// </summary>
        public static string ErrorCode70 {
            get {
                return ResourceManager.GetString("ErrorCode70", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Parsing failed for the following rooms: {List|roomIds}..
        /// </summary>
        public static string ErrorCode72 {
            get {
                return ResourceManager.GetString("ErrorCode72", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to An error occurred while communicating with the service..
        /// </summary>
        public static string ErrorCode73 {
            get {
                return ResourceManager.GetString("ErrorCode73", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to An error occurred while communicating with the connector service..
        /// </summary>
        public static string ErrorCode74 {
            get {
                return ResourceManager.GetString("ErrorCode74", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The sessionId field is required in the request..
        /// </summary>
        public static string ErrorCode8 {
            get {
                return ResourceManager.GetString("ErrorCode8", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The following hotelIds were skipped because they were invalid: {List|hotelIds}..
        /// </summary>
        public static string ErrorCode89 {
            get {
                return ResourceManager.GetString("ErrorCode89", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid country code provided in the request..
        /// </summary>
        public static string ErrorCode92 {
            get {
                return ResourceManager.GetString("ErrorCode92", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The stay duration must be between {int|durationLowerLimit} and {int|durationUpperLimit} nights..
        /// </summary>
        public static string ErrorCode93 {
            get {
                return ResourceManager.GetString("ErrorCode93", resourceCulture);
            }
        }
    }
}
