//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel.Connectors.Hotel.Common.ErrorHandling {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FaultMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal FaultMessages() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Travel.Connectors.Hotel.Common.ErrorHandling.FaultMessages", typeof(FaultMessages).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Advanced booking required. Contact location for reservation..
        /// </summary>
        public static string AdvancedReservation {
            get {
                return ResourceManager.GetString("AdvancedReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to After hours service is not available at this time.
        /// </summary>
        public static string AfterHourService {
            get {
                return ResourceManager.GetString("AfterHourService", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Either the allow object or the disallow object can be set in the {0} filter. You cannot set values for both the objects in one request..
        /// </summary>
        public static string AllowDisallowFilterConstraint {
            get {
                return ResourceManager.GetString("AllowDisallowFilterConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to An application exception occurred..
        /// </summary>
        public static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to DiscountCode is blocked.
        /// </summary>
        public static string BlockedDiscountCode {
            get {
                return ResourceManager.GetString("BlockedDiscountCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to IATA number is blocked.
        /// </summary>
        public static string BlockedIATANumber {
            get {
                return ResourceManager.GetString("BlockedIATANumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to RateCode is blocked.
        /// </summary>
        public static string BlockedRateCode {
            get {
                return ResourceManager.GetString("BlockedRateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to You cannot cancel a booking that is already canceled..
        /// </summary>
        public static string BookingAlreadyCancelled {
            get {
                return ResourceManager.GetString("BookingAlreadyCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to You cannot cancel a booking that does not exist..
        /// </summary>
        public static string BookingDoesNotExist {
            get {
                return ResourceManager.GetString("BookingDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Booking of an allocated vehicle.
        /// </summary>
        public static string BookingVehicleAllocated {
            get {
                return ResourceManager.GetString("BookingVehicleAllocated", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Unable to process the cancellation request. .
        /// </summary>
        public static string CancelFailed {
            get {
                return ResourceManager.GetString("CancelFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Cancellation was already attempted for the given trip id. You cannot attempt the cancellation again..
        /// </summary>
        public static string CancellationAlreadyAttempted {
            get {
                return ResourceManager.GetString("CancellationAlreadyAttempted", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Unable to cancel this reservation.
        /// </summary>
        public static string CancellationFailed {
            get {
                return ResourceManager.GetString("CancellationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Cancellation is not possible at the moment. Please try again later..
        /// </summary>
        public static string CancellationNotPossible {
            get {
                return ResourceManager.GetString("CancellationNotPossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The supplier, {0}, does not support cancellations..
        /// </summary>
        public static string CancellationNotSupported {
            get {
                return ResourceManager.GetString("CancellationNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Failed or Unconfirmed booking cannot be cancelled..
        /// </summary>
        public static string CannotCancelFailedOrUnconfirmedBooking {
            get {
                return ResourceManager.GetString("CannotCancelFailedOrUnconfirmedBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid card holder phone number provided in the request..
        /// </summary>
        public static string CardOwnerPhoneNumberInvalid {
            get {
                return ResourceManager.GetString("CardOwnerPhoneNumberInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The card holder&apos;s  phone number is required in the request..
        /// </summary>
        public static string CardOwnerPhoneNumbersMissing {
            get {
                return ResourceManager.GetString("CardOwnerPhoneNumbersMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Requested car group is not available.
        /// </summary>
        public static string CarGroupNotAvailable {
            get {
                return ResourceManager.GetString("CarGroupNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to No cars available for one way rental.
        /// </summary>
        public static string CarsNotAvailable {
            get {
                return ResourceManager.GetString("CarsNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Requested car is sold out.
        /// </summary>
        public static string CarSoldOut {
            get {
                return ResourceManager.GetString("CarSoldOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Requested car is not supported.
        /// </summary>
        public static string CarTypeNotSupported {
            get {
                return ResourceManager.GetString("CarTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The connector call returned error. .
        /// </summary>
        public static string ConnectorCallFaulted {
            get {
                return ResourceManager.GetString("ConnectorCallFaulted", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Could not fetch the connector configuration requirements for connector : {0}.
        /// </summary>
        public static string ConnectorConfigurationSpecNotFound {
            get {
                return ResourceManager.GetString("ConnectorConfigurationSpecNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The connector identifier is required in the metadata request..
        /// </summary>
        public static string ConnectorIdentifierMissingInMetadataRequest {
            get {
                return ResourceManager.GetString("ConnectorIdentifierMissingInMetadataRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Connector metadata not found for the following suppliers: {0}..
        /// </summary>
        public static string ConnectorMetadataNotFound {
            get {
                return ResourceManager.GetString("ConnectorMetadataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Could not fetch the connector configuration for connector : {0}.
        /// </summary>
        public static string ConnectorReadFailure {
            get {
                return ResourceManager.GetString("ConnectorReadFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to An error occurred while communicating with the connector service..
        /// </summary>
        public static string ConnectorServiceCommunication {
            get {
                return ResourceManager.GetString("ConnectorServiceCommunication", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Error occurred while communicating with {0} consumer service..
        /// </summary>
        public static string ConsumerServiceCommunication {
            get {
                return ResourceManager.GetString("ConsumerServiceCommunication", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to An error occurred while communicating with the content service..
        /// </summary>
        public static string ContentService {
            get {
                return ResourceManager.GetString("ContentService", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Unable to call the content service due to a communication error..
        /// </summary>
        public static string ContentServiceFaulted {
            get {
                return ResourceManager.GetString("ContentServiceFaulted", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Unable to resolve the {0} type. {1}..
        /// </summary>
        public static string CouldNotResolveType {
            get {
                return ResourceManager.GetString("CouldNotResolveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Credit card declined. Either the credit card number is invalid or the merchant blocked the credit card..
        /// </summary>
        public static string CreditCardDeclined {
            get {
                return ResourceManager.GetString("CreditCardDeclined", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The credit card provided has already expired..
        /// </summary>
        public static string CreditCardExpired {
            get {
                return ResourceManager.GetString("CreditCardExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Credit card fraud detected..
        /// </summary>
        public static string CreditCardFraudDetected {
            get {
                return ResourceManager.GetString("CreditCardFraudDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Credit card is not accepted for transaction.
        /// </summary>
        public static string CreditCardNotAccepted {
            get {
                return ResourceManager.GetString("CreditCardNotAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The supplier does not require a credit card payment for this booking..
        /// </summary>
        public static string CreditCardNotRequired {
            get {
                return ResourceManager.GetString("CreditCardNotRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The credit card details are required in the request..
        /// </summary>
        public static string CreditCardRequired {
            get {
                return ResourceManager.GetString("CreditCardRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The supplier, {0}, requires the customer information in the cancellation request..
        /// </summary>
        public static string CustomerInformationRequiredInCancellation {
            get {
                return ResourceManager.GetString("CustomerInformationRequiredInCancellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Requested dates have been closed out.
        /// </summary>
        public static string DatesNotAvailable {
            get {
                return ResourceManager.GetString("DatesNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The dropoff date cannot be earlier than the pickup date..
        /// </summary>
        public static string DropOffPriorToPickupDate {
            get {
                return ResourceManager.GetString("DropOffPriorToPickupDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The dropoff time must be later than the pickup time..
        /// </summary>
        public static string DropOffTimeMustBeGreaterThanPickupTime {
            get {
                return ResourceManager.GetString("DropOffTimeMustBeGreaterThanPickupTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The chosen equipment is unavailable.
        /// </summary>
        public static string EquipmentUnavailable {
            get {
                return ResourceManager.GetString("EquipmentUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The firstName value must be less than {0} characters..
        /// </summary>
        public static string FirstNameLengthExceeded {
            get {
                return ResourceManager.GetString("FirstNameLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Equipment quantity too high.
        /// </summary>
        public static string HighEquipmentQuantity {
            get {
                return ResourceManager.GetString("HighEquipmentQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid tenantId provided in the header..
        /// </summary>
        public static string InvalidAccountId {
            get {
                return ResourceManager.GetString("InvalidAccountId", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid address provided for the customer. .
        /// </summary>
        public static string InvalidAddressInformation {
            get {
                return ResourceManager.GetString("InvalidAddressInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The adult age must be between {0} and {1}..
        /// </summary>
        public static string InvalidAdultAge {
            get {
                return ResourceManager.GetString("InvalidAdultAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Airport code is invalid.
        /// </summary>
        public static string InvalidAirportCode {
            get {
                return ResourceManager.GetString("InvalidAirportCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid amount provided in the booking request. .
        /// </summary>
        public static string InvalidAmountInBookingRequest {
            get {
                return ResourceManager.GetString("InvalidAmountInBookingRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The supplierConfirmationNum field is required in the request..
        /// </summary>
        public static string InvalidBookingConfirmation {
            get {
                return ResourceManager.GetString("InvalidBookingConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Booking contact person age is invalid in {0} Field..
        /// </summary>
        public static string InvalidBookingContactAge {
            get {
                return ResourceManager.GetString("InvalidBookingContactAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Car group is invalid.
        /// </summary>
        public static string InvalidCarGroup {
            get {
                return ResourceManager.GetString("InvalidCarGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid car search criteria.
        /// </summary>
        public static string InvalidCarSearchCriteria {
            get {
                return ResourceManager.GetString("InvalidCarSearchCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to If pickup is requested at rental location, drop off should also be rental location..
        /// </summary>
        public static string InvalidCarSearchPattern {
            get {
                return ResourceManager.GetString("InvalidCarSearchPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to If car rental search is for specific rental location, you cannot specify multiple supplier ids..
        /// </summary>
        public static string InvalidCarSearchSupplierIds {
            get {
                return ResourceManager.GetString("InvalidCarSearchSupplierIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Car type is invalid.
        /// </summary>
        public static string InvalidCarType {
            get {
                return ResourceManager.GetString("InvalidCarType", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to You cannot provide information for the payment field when the paymentType is set to cash. .
        /// </summary>
        public static string InvalidCashFormOfPayment {
            get {
                return ResourceManager.GetString("InvalidCashFormOfPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The check-in date can only be up to a day prior to the current date. .
        /// </summary>
        public static string InvalidCheckInDate {
            get {
                return ResourceManager.GetString("InvalidCheckInDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The latitude and the longitude of the center are required in the request. .
        /// </summary>
        public static string InvalidCircularRegion {
            get {
                return ResourceManager.GetString("InvalidCircularRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Required configurations are missing or invalid..
        /// </summary>
        public static string InvalidConfigurations {
            get {
                return ResourceManager.GetString("InvalidConfigurations", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid connector response..
        /// </summary>
        public static string InvalidConnectorResponse {
            get {
                return ResourceManager.GetString("InvalidConnectorResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid customer contact information provided in the request. .
        /// </summary>
        public static string InvalidContactInformation {
            get {
                return ResourceManager.GetString("InvalidContactInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid correlation Id provided in the header..
        /// </summary>
        public static string InvalidCorrelationId {
            get {
                return ResourceManager.GetString("InvalidCorrelationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid country code provided in the request..
        /// </summary>
        public static string InvalidCountryCode {
            get {
                return ResourceManager.GetString("InvalidCountryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Coverage type is invalid.
        /// </summary>
        public static string InvalidCoverageType {
            get {
                return ResourceManager.GetString("InvalidCoverageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid credentials provided in the supplier request..
        /// </summary>
        public static string InvalidCredentials {
            get {
                return ResourceManager.GetString("InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Credit card is invalid.
        /// </summary>
        public static string InvalidCreditCard {
            get {
                return ResourceManager.GetString("InvalidCreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid credit card details provided in the request. .
        /// </summary>
        public static string InvalidCreditCardDetails {
            get {
                return ResourceManager.GetString("InvalidCreditCardDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid credit card expiry month provided in the request..
        /// </summary>
        public static string InvalidCreditCardExpiryMonth {
            get {
                return ResourceManager.GetString("InvalidCreditCardExpiryMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid credit card expiry year provided in the request..
        /// </summary>
        public static string InvalidCreditCardExpiryYear {
            get {
                return ResourceManager.GetString("InvalidCreditCardExpiryYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The credit card Issuer is not supported..
        /// </summary>
        public static string InvalidCreditCardIssuedBy {
            get {
                return ResourceManager.GetString("InvalidCreditCardIssuedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Name on credit card must match client name..
        /// </summary>
        public static string InvalidCreditCardName {
            get {
                return ResourceManager.GetString("InvalidCreditCardName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The length of credit card num provided is invalid. Length should be greater than or equal to {0}.
        /// </summary>
        public static string InvalidCreditCardNumberLength {
            get {
                return ResourceManager.GetString("InvalidCreditCardNumberLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Incorrect credit card security code provided or the security code validation process failed..
        /// </summary>
        public static string InvalidCreditCardSecureCode {
            get {
                return ResourceManager.GetString("InvalidCreditCardSecureCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Incorrect credit card security code provided. .
        /// </summary>
        public static string InvalidCreditCardSecurityValue {
            get {
                return ResourceManager.GetString("InvalidCreditCardSecurityValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid Credit Id for this location.
        /// </summary>
        public static string InvalidCreditId {
            get {
                return ResourceManager.GetString("InvalidCreditId", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Either no or more than one criteria is provided in the request.
        /// </summary>
        public static string InvalidCriteriaFound {
            get {
                return ResourceManager.GetString("InvalidCriteriaFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid culture provided in the header..
        /// </summary>
        public static string InvalidCulture {
            get {
                return ResourceManager.GetString("InvalidCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid currency provided in the request..
        /// </summary>
        public static string InvalidCurrency {
            get {
                return ResourceManager.GetString("InvalidCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The currency in the booking request must be the same as the currency requested in pricing..
        /// </summary>
        public static string InvalidCurrencyInBookingRequest {
            get {
                return ResourceManager.GetString("InvalidCurrencyInBookingRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The format of the date provided in the {0} field is invalid..
        /// </summary>
        public static string InvalidDate {
            get {
                return ResourceManager.GetString("InvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The {0}.{1} value must be in YYYY-MM-DD format..
        /// </summary>
        public static string InvalidDateTimeFormat {
            get {
                return ResourceManager.GetString("InvalidDateTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Discount code is invalid.
        /// </summary>
        public static string InvalidDiscount {
            get {
                return ResourceManager.GetString("InvalidDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid doorCount provided in the criteria.vehicle  - doorCount value must be 2 or 4.
        /// </summary>
        public static string InvalidDoorCount {
            get {
                return ResourceManager.GetString("InvalidDoorCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The driver&apos;s age must be between {0} and {1}..
        /// </summary>
        public static string InvalidDriverAge {
            get {
                return ResourceManager.GetString("InvalidDriverAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The nationality field has invalid value in the request..
        /// </summary>
        public static string InvalidDriverNationality {
            get {
                return ResourceManager.GetString("InvalidDriverNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Dropoff criteria is either required airport code or rental location.
        /// </summary>
        public static string InvalidDropoffCriteria {
            get {
                return ResourceManager.GetString("InvalidDropoffCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Dropoff date is invalid or past.
        /// </summary>
        public static string InvalidDropoffDate {
            get {
                return ResourceManager.GetString("InvalidDropoffDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Dropoff location is invalid.
        /// </summary>
        public static string InvalidDropoffLocation {
            get {
                return ResourceManager.GetString("InvalidDropoffLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Dropoff time value must be in HH:mm format..
        /// </summary>
        public static string InvalidDropoffTimeFormat {
            get {
                return ResourceManager.GetString("InvalidDropoffTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid email address provided in the request..
        /// </summary>
        public static string InvalidEmailAddress {
            get {
                return ResourceManager.GetString("InvalidEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The value provided in {0} is invalid in the request.
        /// </summary>
        public static string InvalidFieldValue {
            get {
                return ResourceManager.GetString("InvalidFieldValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The firstName value cannot contain special characters. .
        /// </summary>
        public static string InvalidFirstName {
            get {
                return ResourceManager.GetString("InvalidFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid latitude or longitude values. The latitude value must be between -90 to +90 and the longitude value must be between -180 and +180..
        /// </summary>
        public static string InvalidGeocodes {
            get {
                return ResourceManager.GetString("InvalidGeocodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to IATA Number is invalid.
        /// </summary>
        public static string InvalidIATANumber {
            get {
                return ResourceManager.GetString("InvalidIATANumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The lastName value cannot contain special characters. .
        /// </summary>
        public static string InvalidLastName {
            get {
                return ResourceManager.GetString("InvalidLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The maxPrice must be a positive, nonzero value..
        /// </summary>
        public static string InvalidMaxPriceFilter {
            get {
                return ResourceManager.GetString("InvalidMaxPriceFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid loyalty membership information provided in the request..
        /// </summary>
        public static string InvalidMembershipInformation {
            get {
                return ResourceManager.GetString("InvalidMembershipInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Method of Payment is invalid.
        /// </summary>
        public static string InvalidMethodOfPayment {
            get {
                return ResourceManager.GetString("InvalidMethodOfPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The minPrice must be a positive, nonzero value..
        /// </summary>
        public static string InvalidMinPriceFilter {
            get {
                return ResourceManager.GetString("InvalidMinPriceFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid phone information provided for the {0} in the booking request..
        /// </summary>
        public static string InvalidPhoneInformation {
            get {
                return ResourceManager.GetString("InvalidPhoneInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The value of phone type field in the phone is invalid..
        /// </summary>
        public static string InvalidPhoneType {
            get {
                return ResourceManager.GetString("InvalidPhoneType", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Pickup criteria is either required airport code or rental location.
        /// </summary>
        public static string InvalidPickupCriteria {
            get {
                return ResourceManager.GetString("InvalidPickupCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Pickup date is invalid or past.
        /// </summary>
        public static string InvalidPickupDate {
            get {
                return ResourceManager.GetString("InvalidPickupDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Pickup location is invalid.
        /// </summary>
        public static string InvalidPickupLocation {
            get {
                return ResourceManager.GetString("InvalidPickupLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Pickup time value must be in HH:mm format..
        /// </summary>
        public static string InvalidPickupTimeFormat {
            get {
                return ResourceManager.GetString("InvalidPickupTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid posId provided in the request. .
        /// </summary>
        public static string InvalidPosId {
            get {
                return ResourceManager.GetString("InvalidPosId", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid product name provided in the metadata request..
        /// </summary>
        public static string InvalidProductNameInMetadataRequest {
            get {
                return ResourceManager.GetString("InvalidProductNameInMetadataRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The radius must be between 1 and 100..
        /// </summary>
        public static string InvalidRadius {
            get {
                return ResourceManager.GetString("InvalidRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The radius must be between {0} and {1}..
        /// </summary>
        public static string InvalidRadiusForCarSearch {
            get {
                return ResourceManager.GetString("InvalidRadiusForCarSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Rate Code is invalid.
        /// </summary>
        public static string InvalidRateCode {
            get {
                return ResourceManager.GetString("InvalidRateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid rateId provided in the request..
        /// </summary>
        public static string InvalidRateIdFormat {
            get {
                return ResourceManager.GetString("InvalidRateIdFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The car rental duration must not exceed {0} days..
        /// </summary>
        public static string InvalidRentalDuration {
            get {
                return ResourceManager.GetString("InvalidRentalDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Rental Id provided in the request is invalid..
        /// </summary>
        public static string InvalidRentalId {
            get {
                return ResourceManager.GetString("InvalidRentalId", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Rental location is invalid.
        /// </summary>
        public static string InvalidRentalLocation {
            get {
                return ResourceManager.GetString("InvalidRentalLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid request. Verify the request format and then try again..
        /// </summary>
        public static string InvalidRequest {
            get {
                return ResourceManager.GetString("InvalidRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Reservation is invalid.
        /// </summary>
        public static string InvalidReservation {
            get {
                return ResourceManager.GetString("InvalidReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The start date must not be later than {0} days from the current date..
        /// </summary>
        public static string InvalidSearchDate {
            get {
                return ResourceManager.GetString("InvalidSearchDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Either the airport code, geo region, or rental location ID can be provided in the request..
        /// </summary>
        public static string InvalidSearchLocationFormat {
            get {
                return ResourceManager.GetString("InvalidSearchLocationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to You should specify Airport code or Geo region or Rental location Id for pickup/dropoff..
        /// </summary>
        public static string InvalidSearchLocations {
            get {
                return ResourceManager.GetString("InvalidSearchLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid sessionId provided in the request. .
        /// </summary>
        public static string InvalidSessionId {
            get {
                return ResourceManager.GetString("InvalidSessionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid supplierId provided in the request..
        /// </summary>
        public static string InvalidSupplierId {
            get {
                return ResourceManager.GetString("InvalidSupplierId", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid supplierId, {0}, provided in SupplierSpecificOptions..
        /// </summary>
        public static string InvalidSupplierIdInSupplierSpecificOptions {
            get {
                return ResourceManager.GetString("InvalidSupplierIdInSupplierSpecificOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid supplier response. Booking failed..
        /// </summary>
        public static string InvalidSupplierResponse {
            get {
                return ResourceManager.GetString("InvalidSupplierResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The {0} value must be in HH:mm format..
        /// </summary>
        public static string InvalidTimeFormat {
            get {
                return ResourceManager.GetString("InvalidTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The value of title field in the name is invalid..
        /// </summary>
        public static string InvalidTitleInName {
            get {
                return ResourceManager.GetString("InvalidTitleInName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Please verify the token passed in the request. Token value must match the nextToken field from the earlier getResults call..
        /// </summary>
        public static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid {0} provided in the request..
        /// </summary>
        public static string InvalidValueInRequest {
            get {
                return ResourceManager.GetString("InvalidValueInRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to VehicleCategory is invalid in the request.{0}.
        /// </summary>
        public static string InvalidVehicleCategory {
            get {
                return ResourceManager.GetString("InvalidVehicleCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Allow and Disallow vehicle categories must be different.
        /// </summary>
        public static string InvalidVehicleCategoryFilter {
            get {
                return ResourceManager.GetString("InvalidVehicleCategoryFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to VehicleType is invalid in the request.{0}.
        /// </summary>
        public static string InvalidVehicleType {
            get {
                return ResourceManager.GetString("InvalidVehicleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Allow and Disallow vehicle types must be different.
        /// </summary>
        public static string InvalidVehicleTypeFilter {
            get {
                return ResourceManager.GetString("InvalidVehicleTypeFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Allow and Disallow vendors must be different.
        /// </summary>
        public static string InvalidVendorFilter {
            get {
                return ResourceManager.GetString("InvalidVendorFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Vendor name is invalid.
        /// </summary>
        public static string InvalidVendorName {
            get {
                return ResourceManager.GetString("InvalidVendorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to You cannot send multiple vendorSpecificOption for same vendor in the request..
        /// </summary>
        public static string InvalidVendorSpecificOptions {
            get {
                return ResourceManager.GetString("InvalidVendorSpecificOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid version provided in the supplier request..
        /// </summary>
        public static string InvalidVersion {
            get {
                return ResourceManager.GetString("InvalidVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The Ip Address is either missing or is in invalid format..
        /// </summary>
        public static string IpAddressMissingOrInvalid {
            get {
                return ResourceManager.GetString("IpAddressMissingOrInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The lastName value must be less than {0} characters..
        /// </summary>
        public static string LastNameLengthExceeded {
            get {
                return ResourceManager.GetString("LastNameLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Data Lookup failed for &apos;{0}&apos; for Id: &apos;{1}&apos;..
        /// </summary>
        public static string LookUpFailed {
            get {
                return ResourceManager.GetString("LookUpFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to No vehicle found matching the request.
        /// </summary>
        public static string MatchingVehicleNotFound {
            get {
                return ResourceManager.GetString("MatchingVehicleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to An error occurred while using the metadata..
        /// </summary>
        public static string Metadata {
            get {
                return ResourceManager.GetString("Metadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The minPrice value must be lower than the maxPrice value. .
        /// </summary>
        public static string MinPriceGreaterThanMax {
            get {
                return ResourceManager.GetString("MinPriceGreaterThanMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The city name or code fields are required in the request.{0} .
        /// </summary>
        public static string MissingAddressCity {
            get {
                return ResourceManager.GetString("MissingAddressCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The address countryCode field is required in the request.{0} .
        /// </summary>
        public static string MissingAddressCountryCode {
            get {
                return ResourceManager.GetString("MissingAddressCountryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The customer address line1 field is required in the request. .
        /// </summary>
        public static string MissingAddressLine {
            get {
                return ResourceManager.GetString("MissingAddressLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The address line1 field is required in the request.{0} .
        /// </summary>
        public static string MissingAddressLine1 {
            get {
                return ResourceManager.GetString("MissingAddressLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The address postalCode field is required in the request.{0} .
        /// </summary>
        public static string MissingAddressPostalCode {
            get {
                return ResourceManager.GetString("MissingAddressPostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Airport code is required field in request..
        /// </summary>
        public static string MissingAirportCode {
            get {
                return ResourceManager.GetString("MissingAirportCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The vehicleCategory field is required in the vehicleCategory.allow filter..
        /// </summary>
        public static string MissingAllowedVehicleCategoriesInFilter {
            get {
                return ResourceManager.GetString("MissingAllowedVehicleCategoriesInFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The vehicleType field is required in the vehicleType.allow filter..
        /// </summary>
        public static string MissingAllowedVehicleTypesInFilter {
            get {
                return ResourceManager.GetString("MissingAllowedVehicleTypesInFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The credit card billing address city details are required in the request..
        /// </summary>
        public static string MissingBillingAddressCity {
            get {
                return ResourceManager.GetString("MissingBillingAddressCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Credit Card Billing Address City Name is Missing..
        /// </summary>
        public static string MissingBillingAddressCityName {
            get {
                return ResourceManager.GetString("MissingBillingAddressCityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The credit card billing address countryCode field is required in the request..
        /// </summary>
        public static string MissingBillingAddressCountryCode {
            get {
                return ResourceManager.GetString("MissingBillingAddressCountryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The credit card billing address line1 field is required in the request..
        /// </summary>
        public static string MissingBillingAddressLine1 {
            get {
                return ResourceManager.GetString("MissingBillingAddressLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The credit card billing address postalCode field is required in the request..
        /// </summary>
        public static string MissingBillingAddressPostalCode {
            get {
                return ResourceManager.GetString("MissingBillingAddressPostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Credit Card Billing Address State Code is Missing..
        /// </summary>
        public static string MissingBillingAddressStateCode {
            get {
                return ResourceManager.GetString("MissingBillingAddressStateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The booking contact person name information is missing in the {0} field..
        /// </summary>
        public static string MissingBookingContactNameInformation {
            get {
                return ResourceManager.GetString("MissingBookingContactNameInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Booking contact phone details like number , extentions is missing..
        /// </summary>
        public static string MissingBookingContactPhoneDetails {
            get {
                return ResourceManager.GetString("MissingBookingContactPhoneDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Booking contact phone number is missing..
        /// </summary>
        public static string MissingBookingContactPhoneNumber {
            get {
                return ResourceManager.GetString("MissingBookingContactPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The customer city name or code fields are required in the request..
        /// </summary>
        public static string MissingCityInformation {
            get {
                return ResourceManager.GetString("MissingCityInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid connector metadata. The following details are missing: {0}..
        /// </summary>
        public static string MissingConnectorMetadata {
            get {
                return ResourceManager.GetString("MissingConnectorMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The customer firstName field is required in the request. .
        /// </summary>
        public static string MissingContactFirstName {
            get {
                return ResourceManager.GetString("MissingContactFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The customer lastName field is required in the request. .
        /// </summary>
        public static string MissingContactLastName {
            get {
                return ResourceManager.GetString("MissingContactLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The customer countryCode field is required in the request..
        /// </summary>
        public static string MissingCountryCode {
            get {
                return ResourceManager.GetString("MissingCountryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The credit card billing address field is required in the request..
        /// </summary>
        public static string MissingCreditCardBillingAddress {
            get {
                return ResourceManager.GetString("MissingCreditCardBillingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The credit card cvv field is required in the request..
        /// </summary>
        public static string MissingCreditCardCvv {
            get {
                return ResourceManager.GetString("MissingCreditCardCvv", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The credit card expiry month and year fields are required in the request..
        /// </summary>
        public static string MissingCreditCardExpiryDate {
            get {
                return ResourceManager.GetString("MissingCreditCardExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Credit card Issuer Missing. Please add valid credit card issuer..
        /// </summary>
        public static string MissingCreditCardIssuedBy {
            get {
                return ResourceManager.GetString("MissingCreditCardIssuedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The credit card num field is required in the request..
        /// </summary>
        public static string MissingCreditCardNumber {
            get {
                return ResourceManager.GetString("MissingCreditCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The credit card billing address state name and code fields are required in the request..
        /// </summary>
        public static string MissingCreditCardStateDetails {
            get {
                return ResourceManager.GetString("MissingCreditCardStateDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Criteria is required in the request..
        /// </summary>
        public static string MissingCriteria {
            get {
                return ResourceManager.GetString("MissingCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The currency is missing in the request..
        /// </summary>
        public static string MissingCurrency {
            get {
                return ResourceManager.GetString("MissingCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The customer field is required in the booking request..
        /// </summary>
        public static string MissingCustomerInformationInBooking {
            get {
                return ResourceManager.GetString("MissingCustomerInformationInBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Customer name field is required in the request. .
        /// </summary>
        public static string MissingCustomerName {
            get {
                return ResourceManager.GetString("MissingCustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The dob field is required in the request..
        /// </summary>
        public static string MissingDateOfBirth {
            get {
                return ResourceManager.GetString("MissingDateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The following details are required in the cancellation request: {0}..
        /// </summary>
        public static string MissingDetailsInCancellation {
            get {
                return ResourceManager.GetString("MissingDetailsInCancellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The vehicleCategory field is required in the vehicleCategory.disallow filter..
        /// </summary>
        public static string MissingDisAllowedVehicleCategoriesInFilter {
            get {
                return ResourceManager.GetString("MissingDisAllowedVehicleCategoriesInFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The vehicleType is required in the vehicleType.disallow filter..
        /// </summary>
        public static string MissingDisAllowedVehicleTypesInFilter {
            get {
                return ResourceManager.GetString("MissingDisAllowedVehicleTypesInFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Either the promoCode, rateCode, or corporateCode field is required in the vendorSpecificOptions field..
        /// </summary>
        public static string MissingDiscountCodes {
            get {
                return ResourceManager.GetString("MissingDiscountCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The doorCount is required in the criteria.vehicle.
        /// </summary>
        public static string MissingDoorCount {
            get {
                return ResourceManager.GetString("MissingDoorCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Driver age is required in request.
        /// </summary>
        public static string MissingDriverAge {
            get {
                return ResourceManager.GetString("MissingDriverAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Driver information is required in request.
        /// </summary>
        public static string MissingDriverInfo {
            get {
                return ResourceManager.GetString("MissingDriverInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The driver&apos;s nationality is required in the request..
        /// </summary>
        public static string MissingDriverNationality {
            get {
                return ResourceManager.GetString("MissingDriverNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Either dropoff airport code or rental location is required in request.
        /// </summary>
        public static string MissingDropoffAirportOrRentalLocationCode {
            get {
                return ResourceManager.GetString("MissingDropoffAirportOrRentalLocationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Dropoff date is required in request.
        /// </summary>
        public static string MissingDropoffDate {
            get {
                return ResourceManager.GetString("MissingDropoffDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Dropoff location is required in request.
        /// </summary>
        public static string MissingDropoffLocation {
            get {
                return ResourceManager.GetString("MissingDropoffLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Missing dropoff rental location code in the request..
        /// </summary>
        public static string MissingDropoffRentalLocationCode {
            get {
                return ResourceManager.GetString("MissingDropoffRentalLocationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The customer email field is required in the request..
        /// </summary>
        public static string MissingEmailInformation {
            get {
                return ResourceManager.GetString("MissingEmailInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The Configuration : {0} is missing in consul for {1} service..
        /// </summary>
        public static string MissingExternalServiceConfiguration {
            get {
                return ResourceManager.GetString("MissingExternalServiceConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The value for {0} is missing in the request.
        /// </summary>
        public static string MissingField {
            get {
                return ResourceManager.GetString("MissingField", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The {0} code is required in the request. .
        /// </summary>
        public static string MissingLocationCode {
            get {
                return ResourceManager.GetString("MissingLocationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The {0} name is required in the request. .
        /// </summary>
        public static string MissingLocationName {
            get {
                return ResourceManager.GetString("MissingLocationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The nameOnCard field is required in the request. .
        /// </summary>
        public static string MissingNameOnCreditCard {
            get {
                return ResourceManager.GetString("MissingNameOnCreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The nationality field is required in the request..
        /// </summary>
        public static string MissingNationality {
            get {
                return ResourceManager.GetString("MissingNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to PaymentType is required in the request..
        /// </summary>
        public static string MissingPaymentType {
            get {
                return ResourceManager.GetString("MissingPaymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Either pickup airport code or rental location is required in request.
        /// </summary>
        public static string MissingPickupAirportOrRentalLocationCode {
            get {
                return ResourceManager.GetString("MissingPickupAirportOrRentalLocationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Pickup date is required in request.
        /// </summary>
        public static string MissingPickupDate {
            get {
                return ResourceManager.GetString("MissingPickupDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Pickup location is required in request.
        /// </summary>
        public static string MissingPickupLocation {
            get {
                return ResourceManager.GetString("MissingPickupLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Missing pickup rental location code in the request..
        /// </summary>
        public static string MissingPickupRentalLocationCode {
            get {
                return ResourceManager.GetString("MissingPickupRentalLocationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Rate Code is required in request.
        /// </summary>
        public static string MissingRateCode {
            get {
                return ResourceManager.GetString("MissingRateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The rateIds are required in the request. .
        /// </summary>
        public static string MissingRateIds {
            get {
                return ResourceManager.GetString("MissingRateIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The rateRefId field is required in the request. .
        /// </summary>
        public static string MissingRateReferenceId {
            get {
                return ResourceManager.GetString("MissingRateReferenceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Rental Id missing in the request..
        /// </summary>
        public static string MissingRentalId {
            get {
                return ResourceManager.GetString("MissingRentalId", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The rentalLocationId field is required in the request..
        /// </summary>
        public static string MissingRentalLocationId {
            get {
                return ResourceManager.GetString("MissingRentalLocationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The rateId field is required in the request..
        /// </summary>
        public static string MissingRoomRate {
            get {
                return ResourceManager.GetString("MissingRoomRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The sessionId field is required in the request..
        /// </summary>
        public static string MissingSessionId {
            get {
                return ResourceManager.GetString("MissingSessionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The state field for the address is required in the request..
        /// </summary>
        public static string MissingStateInformation {
            get {
                return ResourceManager.GetString("MissingStateInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The following supplier configuration details are required in the request: {0}..
        /// </summary>
        public static string MissingSupplierConfiguration {
            get {
                return ResourceManager.GetString("MissingSupplierConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Unable to find the supplier configuration. .
        /// </summary>
        public static string MissingSupplierConfigurations {
            get {
                return ResourceManager.GetString("MissingSupplierConfigurations", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The supplier details are required in the request. .
        /// </summary>
        public static string MissingSupplierDetails {
            get {
                return ResourceManager.GetString("MissingSupplierDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The supplierId field is required in the request..
        /// </summary>
        public static string MissingSupplierId {
            get {
                return ResourceManager.GetString("MissingSupplierId", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The supplierName field is required in the request..
        /// </summary>
        public static string MissingSupplierName {
            get {
                return ResourceManager.GetString("MissingSupplierName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The following tenant configuration details are required: {0}..
        /// </summary>
        public static string MissingTenantConfigurations {
            get {
                return ResourceManager.GetString("MissingTenantConfigurations", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The tenantId field is required in the request..
        /// </summary>
        public static string MissingTenantId {
            get {
                return ResourceManager.GetString("MissingTenantId", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The title field is required in the name..
        /// </summary>
        public static string MissingTitleInName {
            get {
                return ResourceManager.GetString("MissingTitleInName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Vehicle Category is missing or invalid in the request.
        /// </summary>
        public static string MissingVehicleCategory {
            get {
                return ResourceManager.GetString("MissingVehicleCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Vehicle information is required in request.
        /// </summary>
        public static string MissingVehicleDetails {
            get {
                return ResourceManager.GetString("MissingVehicleDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Vehicle SippCode  is required in request.
        /// </summary>
        public static string MissingVehicleSippCode {
            get {
                return ResourceManager.GetString("MissingVehicleSippCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Vehicle Transmission is missing or invalid in the request.
        /// </summary>
        public static string MissingVehicleTransmission {
            get {
                return ResourceManager.GetString("MissingVehicleTransmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Vehicle Type is missing or invalid in the request.
        /// </summary>
        public static string MissingVehicleType {
            get {
                return ResourceManager.GetString("MissingVehicleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Vendor code is required in request.
        /// </summary>
        public static string MissingVendorCode {
            get {
                return ResourceManager.GetString("MissingVendorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Requested make/model is not available..
        /// </summary>
        public static string ModelNotAvailable {
            get {
                return ResourceManager.GetString("ModelNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Credit card can not be modified.
        /// </summary>
        public static string ModifiedCreditCard {
            get {
                return ResourceManager.GetString("ModifiedCreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Multiple form of payment is not allowed. Single form of payment accepted.
        /// </summary>
        public static string MultiFormOfPaymentNotAllowed {
            get {
                return ResourceManager.GetString("MultiFormOfPaymentNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to No booking found with the given trip id..
        /// </summary>
        public static string NoBookingFoundForCancellation {
            get {
                return ResourceManager.GetString("NoBookingFoundForCancellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Cancellation not allowed for this booking.
        /// </summary>
        public static string NonCancellableBooking {
            get {
                return ResourceManager.GetString("NonCancellableBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to No rental locations found for given search criteria..
        /// </summary>
        public static string NoRentalLocationsForGivenCriteria {
            get {
                return ResourceManager.GetString("NoRentalLocationsForGivenCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to There are no results for the search criteria provided. .
        /// </summary>
        public static string NoResultsForSearchCriteria {
            get {
                return ResourceManager.GetString("NoResultsForSearchCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to There are no search results found or all the search results are filtered out..
        /// </summary>
        public static string NoResultsOrAllResultsFilteredOut {
            get {
                return ResourceManager.GetString("NoResultsOrAllResultsFilteredOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The supplier does not allow online cancellation for this booking. .
        /// </summary>
        public static string NoSupportForOnlineCancellation {
            get {
                return ResourceManager.GetString("NoSupportForOnlineCancellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Unfortunately this oneway rental is not permitted.
        /// </summary>
        public static string OneWayRentalNotPermitted {
            get {
                return ResourceManager.GetString("OneWayRentalNotPermitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Package Unavailable.
        /// </summary>
        public static string PackageUnavailable {
            get {
                return ResourceManager.GetString("PackageUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Unable to parse supplier response..
        /// </summary>
        public static string ParsingFailure {
            get {
                return ResourceManager.GetString("ParsingFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Customer can only cancel by phone.
        /// </summary>
        public static string PhoneCancellation {
            get {
                return ResourceManager.GetString("PhoneCancellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The booking failed because the room price recently changed..
        /// </summary>
        public static string PricesChanged {
            get {
                return ResourceManager.GetString("PricesChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Number of request exceeded allowed limit..
        /// </summary>
        public static string RateLimitExceeded {
            get {
                return ResourceManager.GetString("RateLimitExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Rate not available.
        /// </summary>
        public static string RateNotAvailble {
            get {
                return ResourceManager.GetString("RateNotAvailble", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Rental must include one weekday.
        /// </summary>
        public static string RentalIncludeWeekday {
            get {
                return ResourceManager.GetString("RentalIncludeWeekday", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Rental must include a weekend.
        /// </summary>
        public static string RentalIncludeWeekend {
            get {
                return ResourceManager.GetString("RentalIncludeWeekend", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Rental period limit is exceeded.
        /// </summary>
        public static string RentalPeriodLimitExceeds {
            get {
                return ResourceManager.GetString("RentalPeriodLimitExceeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Rental terms aren&apos;t available at the moment. Please try again later..
        /// </summary>
        public static string RentalTermsNotAvailable {
            get {
                return ResourceManager.GetString("RentalTermsNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to No request found. You must provide a valid request..
        /// </summary>
        public static string RequestNotFound {
            get {
                return ResourceManager.GetString("RequestNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to An error occurred while processing the request..
        /// </summary>
        public static string RequestProcessingError {
            get {
                return ResourceManager.GetString("RequestProcessingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Reservation was already cancelled.
        /// </summary>
        public static string ReservationCancelled {
            get {
                return ResourceManager.GetString("ReservationCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Reservation already exists.
        /// </summary>
        public static string ReservationExists {
            get {
                return ResourceManager.GetString("ReservationExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Unable to make a reservation.
        /// </summary>
        public static string ReservationFailed {
            get {
                return ResourceManager.GetString("ReservationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Unable to retrieve the reservation details.
        /// </summary>
        public static string RetrieveReservationFailed {
            get {
                return ResourceManager.GetString("RetrieveReservationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to An error occurred while communicating with the service..
        /// </summary>
        public static string ServiceCommunication {
            get {
                return ResourceManager.GetString("ServiceCommunication", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to An error occurred while reading data from the session store..
        /// </summary>
        public static string SessionStoreRead {
            get {
                return ResourceManager.GetString("SessionStoreRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to An error occurred while writing data to the session store..
        /// </summary>
        public static string SessionStoreWrite {
            get {
                return ResourceManager.GetString("SessionStoreWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to No previous state found for this request. You must initiate search once again. .
        /// </summary>
        public static string StateNotFound {
            get {
                return ResourceManager.GetString("StateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Rental location station closed.
        /// </summary>
        public static string StationClosed {
            get {
                return ResourceManager.GetString("StationClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to A supplier exception occurred..
        /// </summary>
        public static string Supplier {
            get {
                return ResourceManager.GetString("Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Could not call any supplier, this might be either because of configuration issues or supplier request validation failures..
        /// </summary>
        public static string SupplierCommunication {
            get {
                return ResourceManager.GetString("SupplierCommunication", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The supplier configuration is not available for the following supplierIds: {0}..
        /// </summary>
        public static string SupplierConfigurationNotAvailable {
            get {
                return ResourceManager.GetString("SupplierConfigurationNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} supplier is disabled. No operation executed on this supplier.
        /// </summary>
        public static string SupplierDisabled {
            get {
                return ResourceManager.GetString("SupplierDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Unable to process the request due to an unexpected supplier exception. .
        /// </summary>
        public static string SupplierException {
            get {
                return ResourceManager.GetString("SupplierException", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The supplier server is unreachable. Try again after some time..
        /// </summary>
        public static string SupplierServerDown {
            get {
                return ResourceManager.GetString("SupplierServerDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to An error occurred at the supplier&apos;s side. Try again after some time..
        /// </summary>
        public static string SupplierSystem {
            get {
                return ResourceManager.GetString("SupplierSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The supplier returned validation errors. .
        /// </summary>
        public static string SupplierValidation {
            get {
                return ResourceManager.GetString("SupplierValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to A system error occurred. Try again after some time..
        /// </summary>
        public static string System {
            get {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Unable to read the tenant configuration..
        /// </summary>
        public static string TenantConfigurationRead {
            get {
                return ResourceManager.GetString("TenantConfigurationRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to No tenant found with tenantId {0}..
        /// </summary>
        public static string TenantNotFound {
            get {
                return ResourceManager.GetString("TenantNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to A timeout exception occurred..
        /// </summary>
        public static string TimeOut {
            get {
                return ResourceManager.GetString("TimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Translation missing for type {0}..
        /// </summary>
        public static string TranslationMissing {
            get {
                return ResourceManager.GetString("TranslationMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Travel between these stations is not permitted.
        /// </summary>
        public static string TravelBetweenStationsNotPermitted {
            get {
                return ResourceManager.GetString("TravelBetweenStationsNotPermitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Unable to process the transaction.
        /// </summary>
        public static string UnableToTransact {
            get {
                return ResourceManager.GetString("UnableToTransact", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to An internal server error occured. Check the logs for more details.
        /// </summary>
        public static string UnexpectedSystemException {
            get {
                return ResourceManager.GetString("UnexpectedSystemException", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The following supplier exception occurred: {0}. This exception does not map with any existing supplier error..
        /// </summary>
        public static string UnMappedSupplier {
            get {
                return ResourceManager.GetString("UnMappedSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The supplier does not support the {0} culture..
        /// </summary>
        public static string UnSupportedCulture {
            get {
                return ResourceManager.GetString("UnSupportedCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The supplier does not support loyalty memberships..
        /// </summary>
        public static string UnSupportedLoyaltyMembership {
            get {
                return ResourceManager.GetString("UnSupportedLoyaltyMembership", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The supplier does not support the following rate types: {0}..
        /// </summary>
        public static string UnSupportedRateTypes {
            get {
                return ResourceManager.GetString("UnSupportedRateTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The supplier does not support special requests. .
        /// </summary>
        public static string UnSupportedSpecialRequest {
            get {
                return ResourceManager.GetString("UnSupportedSpecialRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The following validation errors occurred: .
        /// </summary>
        public static string ValidationFailure {
            get {
                return ResourceManager.GetString("ValidationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Requested vehicle class not supported.
        /// </summary>
        public static string VehicleClassNotSupported {
            get {
                return ResourceManager.GetString("VehicleClassNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Requested vehicle type not supported.
        /// </summary>
        public static string VehicleTypeNotSupported {
            get {
                return ResourceManager.GetString("VehicleTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid connector identifier, {0}, provided in the request..
        /// </summary>
        public static string WrongConnectorIdentifier {
            get {
                return ResourceManager.GetString("WrongConnectorIdentifier", resourceCulture);
            }
        }
    }
}
