//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel.Connectors.Hotel.Common.ErrorHandling {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FaultCodes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal FaultCodes() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Travel.Connectors.Hotel.Common.ErrorHandling.FaultCodes", typeof(FaultCodes).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 576.
        /// </summary>
        public static string AdvancedReservation {
            get {
                return ResourceManager.GetString("AdvancedReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 615.
        /// </summary>
        public static string AfterHourService {
            get {
                return ResourceManager.GetString("AfterHourService", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 623.
        /// </summary>
        public static string AllowDisallowFilterConstraint {
            get {
                return ResourceManager.GetString("AllowDisallowFilterConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 34.
        /// </summary>
        public static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 544.
        /// </summary>
        public static string BlockedDiscountCode {
            get {
                return ResourceManager.GetString("BlockedDiscountCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 545.
        /// </summary>
        public static string BlockedIATANumber {
            get {
                return ResourceManager.GetString("BlockedIATANumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 543.
        /// </summary>
        public static string BlockedRateCode {
            get {
                return ResourceManager.GetString("BlockedRateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 201.
        /// </summary>
        public static string BookingAlreadyCancelled {
            get {
                return ResourceManager.GetString("BookingAlreadyCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 200.
        /// </summary>
        public static string BookingDoesNotExist {
            get {
                return ResourceManager.GetString("BookingDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 612.
        /// </summary>
        public static string BookingVehicleAllocated {
            get {
                return ResourceManager.GetString("BookingVehicleAllocated", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 315.
        /// </summary>
        public static string CancelFailed {
            get {
                return ResourceManager.GetString("CancelFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 624.
        /// </summary>
        public static string CancellationAlreadyAttempted {
            get {
                return ResourceManager.GetString("CancellationAlreadyAttempted", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 554.
        /// </summary>
        public static string CancellationFailed {
            get {
                return ResourceManager.GetString("CancellationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 616.
        /// </summary>
        public static string CancellationNotPossible {
            get {
                return ResourceManager.GetString("CancellationNotPossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 209.
        /// </summary>
        public static string CancellationNotSupported {
            get {
                return ResourceManager.GetString("CancellationNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 626.
        /// </summary>
        public static string CannotCancelFailedOrUnconfirmedBooking {
            get {
                return ResourceManager.GetString("CannotCancelFailedOrUnconfirmedBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 306.
        /// </summary>
        public static string CardOwnerPhoneNumberInvalid {
            get {
                return ResourceManager.GetString("CardOwnerPhoneNumberInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 305.
        /// </summary>
        public static string CardOwnerPhoneNumbersMissing {
            get {
                return ResourceManager.GetString("CardOwnerPhoneNumbersMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 574.
        /// </summary>
        public static string CarGroupNotAvailable {
            get {
                return ResourceManager.GetString("CarGroupNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 572.
        /// </summary>
        public static string CarsNotAvailable {
            get {
                return ResourceManager.GetString("CarsNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 569.
        /// </summary>
        public static string CarSoldOut {
            get {
                return ResourceManager.GetString("CarSoldOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 550.
        /// </summary>
        public static string CarTypeNotSupported {
            get {
                return ResourceManager.GetString("CarTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 48.
        /// </summary>
        public static string ConnectorCallFaulted {
            get {
                return ResourceManager.GetString("ConnectorCallFaulted", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 366.
        /// </summary>
        public static string ConnectorConfigurationSpecNotFound {
            get {
                return ResourceManager.GetString("ConnectorConfigurationSpecNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 310.
        /// </summary>
        public static string ConnectorIdentifierMissingInMetadataRequest {
            get {
                return ResourceManager.GetString("ConnectorIdentifierMissingInMetadataRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 38.
        /// </summary>
        public static string ConnectorMetadataNotFound {
            get {
                return ResourceManager.GetString("ConnectorMetadataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 363.
        /// </summary>
        public static string ConnectorReadFailure {
            get {
                return ResourceManager.GetString("ConnectorReadFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 74.
        /// </summary>
        public static string ConnectorServiceCommunication {
            get {
                return ResourceManager.GetString("ConnectorServiceCommunication", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 337.
        /// </summary>
        public static string ConsumerServiceCommunication {
            get {
                return ResourceManager.GetString("ConsumerServiceCommunication", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 198.
        /// </summary>
        public static string ContentService {
            get {
                return ResourceManager.GetString("ContentService", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 197.
        /// </summary>
        public static string ContentServiceFaulted {
            get {
                return ResourceManager.GetString("ContentServiceFaulted", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 63.
        /// </summary>
        public static string CouldNotResolveType {
            get {
                return ResourceManager.GetString("CouldNotResolveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 190.
        /// </summary>
        public static string CreditCardDeclined {
            get {
                return ResourceManager.GetString("CreditCardDeclined", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 163.
        /// </summary>
        public static string CreditCardExpired {
            get {
                return ResourceManager.GetString("CreditCardExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 203.
        /// </summary>
        public static string CreditCardFraudDetected {
            get {
                return ResourceManager.GetString("CreditCardFraudDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 560.
        /// </summary>
        public static string CreditCardNotAccepted {
            get {
                return ResourceManager.GetString("CreditCardNotAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 137.
        /// </summary>
        public static string CreditCardNotRequired {
            get {
                return ResourceManager.GetString("CreditCardNotRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 138.
        /// </summary>
        public static string CreditCardRequired {
            get {
                return ResourceManager.GetString("CreditCardRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 210.
        /// </summary>
        public static string CustomerInformationRequiredInCancellation {
            get {
                return ResourceManager.GetString("CustomerInformationRequiredInCancellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 568.
        /// </summary>
        public static string DatesNotAvailable {
            get {
                return ResourceManager.GetString("DatesNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 515.
        /// </summary>
        public static string DropOffPriorToPickupDate {
            get {
                return ResourceManager.GetString("DropOffPriorToPickupDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 584.
        /// </summary>
        public static string DropOffTimeMustBeGreaterThanPickupTime {
            get {
                return ResourceManager.GetString("DropOffTimeMustBeGreaterThanPickupTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 608.
        /// </summary>
        public static string EquipmentUnavailable {
            get {
                return ResourceManager.GetString("EquipmentUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 142.
        /// </summary>
        public static string FirstNameLengthExceeded {
            get {
                return ResourceManager.GetString("FirstNameLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 614.
        /// </summary>
        public static string HighEquipmentQuantity {
            get {
                return ResourceManager.GetString("HighEquipmentQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 2.
        /// </summary>
        public static string InvalidAccountId {
            get {
                return ResourceManager.GetString("InvalidAccountId", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 152.
        /// </summary>
        public static string InvalidAddressInformation {
            get {
                return ResourceManager.GetString("InvalidAddressInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 224.
        /// </summary>
        public static string InvalidAdultAge {
            get {
                return ResourceManager.GetString("InvalidAdultAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 547.
        /// </summary>
        public static string InvalidAirportCode {
            get {
                return ResourceManager.GetString("InvalidAirportCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 289.
        /// </summary>
        public static string InvalidAmountInBookingRequest {
            get {
                return ResourceManager.GetString("InvalidAmountInBookingRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 205.
        /// </summary>
        public static string InvalidBookingConfirmation {
            get {
                return ResourceManager.GetString("InvalidBookingConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 333.
        /// </summary>
        public static string InvalidBookingContactAge {
            get {
                return ResourceManager.GetString("InvalidBookingContactAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 542.
        /// </summary>
        public static string InvalidCarGroup {
            get {
                return ResourceManager.GetString("InvalidCarGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 516.
        /// </summary>
        public static string InvalidCarSearchCriteria {
            get {
                return ResourceManager.GetString("InvalidCarSearchCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 536.
        /// </summary>
        public static string InvalidCarSearchPattern {
            get {
                return ResourceManager.GetString("InvalidCarSearchPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 537.
        /// </summary>
        public static string InvalidCarSearchSupplierIds {
            get {
                return ResourceManager.GetString("InvalidCarSearchSupplierIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 563.
        /// </summary>
        public static string InvalidCarType {
            get {
                return ResourceManager.GetString("InvalidCarType", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 440.
        /// </summary>
        public static string InvalidCashFormOfPayment {
            get {
                return ResourceManager.GetString("InvalidCashFormOfPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 23.
        /// </summary>
        public static string InvalidCheckInDate {
            get {
                return ResourceManager.GetString("InvalidCheckInDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 46.
        /// </summary>
        public static string InvalidCircularRegion {
            get {
                return ResourceManager.GetString("InvalidCircularRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 49.
        /// </summary>
        public static string InvalidConfigurations {
            get {
                return ResourceManager.GetString("InvalidConfigurations", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 126.
        /// </summary>
        public static string InvalidConnectorResponse {
            get {
                return ResourceManager.GetString("InvalidConnectorResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 150.
        /// </summary>
        public static string InvalidContactInformation {
            get {
                return ResourceManager.GetString("InvalidContactInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 497.
        /// </summary>
        public static string InvalidCorrelationId {
            get {
                return ResourceManager.GetString("InvalidCorrelationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 92.
        /// </summary>
        public static string InvalidCountryCode {
            get {
                return ResourceManager.GetString("InvalidCountryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 551.
        /// </summary>
        public static string InvalidCoverageType {
            get {
                return ResourceManager.GetString("InvalidCoverageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 41.
        /// </summary>
        public static string InvalidCredentials {
            get {
                return ResourceManager.GetString("InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 564.
        /// </summary>
        public static string InvalidCreditCard {
            get {
                return ResourceManager.GetString("InvalidCreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 183.
        /// </summary>
        public static string InvalidCreditCardDetails {
            get {
                return ResourceManager.GetString("InvalidCreditCardDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 178.
        /// </summary>
        public static string InvalidCreditCardExpiryMonth {
            get {
                return ResourceManager.GetString("InvalidCreditCardExpiryMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 179.
        /// </summary>
        public static string InvalidCreditCardExpiryYear {
            get {
                return ResourceManager.GetString("InvalidCreditCardExpiryYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 136.
        /// </summary>
        public static string InvalidCreditCardIssuedBy {
            get {
                return ResourceManager.GetString("InvalidCreditCardIssuedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 611.
        /// </summary>
        public static string InvalidCreditCardName {
            get {
                return ResourceManager.GetString("InvalidCreditCardName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 452.
        /// </summary>
        public static string InvalidCreditCardNumberLength {
            get {
                return ResourceManager.GetString("InvalidCreditCardNumberLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 194.
        /// </summary>
        public static string InvalidCreditCardSecureCode {
            get {
                return ResourceManager.GetString("InvalidCreditCardSecureCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 193.
        /// </summary>
        public static string InvalidCreditCardSecurityValue {
            get {
                return ResourceManager.GetString("InvalidCreditCardSecurityValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 567.
        /// </summary>
        public static string InvalidCreditId {
            get {
                return ResourceManager.GetString("InvalidCreditId", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 522.
        /// </summary>
        public static string InvalidCriteriaFound {
            get {
                return ResourceManager.GetString("InvalidCriteriaFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 117.
        /// </summary>
        public static string InvalidCulture {
            get {
                return ResourceManager.GetString("InvalidCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 3.
        /// </summary>
        public static string InvalidCurrency {
            get {
                return ResourceManager.GetString("InvalidCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 292.
        /// </summary>
        public static string InvalidCurrencyInBookingRequest {
            get {
                return ResourceManager.GetString("InvalidCurrencyInBookingRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 472.
        /// </summary>
        public static string InvalidDate {
            get {
                return ResourceManager.GetString("InvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 487.
        /// </summary>
        public static string InvalidDateTimeFormat {
            get {
                return ResourceManager.GetString("InvalidDateTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 541.
        /// </summary>
        public static string InvalidDiscount {
            get {
                return ResourceManager.GetString("InvalidDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 629.
        /// </summary>
        public static string InvalidDoorCount {
            get {
                return ResourceManager.GetString("InvalidDoorCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 534.
        /// </summary>
        public static string InvalidDriverAge {
            get {
                return ResourceManager.GetString("InvalidDriverAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 526.
        /// </summary>
        public static string InvalidDriverNationality {
            get {
                return ResourceManager.GetString("InvalidDriverNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 509.
        /// </summary>
        public static string InvalidDropoffCriteria {
            get {
                return ResourceManager.GetString("InvalidDropoffCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 506.
        /// </summary>
        public static string InvalidDropoffDate {
            get {
                return ResourceManager.GetString("InvalidDropoffDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 530.
        /// </summary>
        public static string InvalidDropoffLocation {
            get {
                return ResourceManager.GetString("InvalidDropoffLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 507.
        /// </summary>
        public static string InvalidDropoffTimeFormat {
            get {
                return ResourceManager.GetString("InvalidDropoffTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 277.
        /// </summary>
        public static string InvalidEmailAddress {
            get {
                return ResourceManager.GetString("InvalidEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 597.
        /// </summary>
        public static string InvalidFieldValue {
            get {
                return ResourceManager.GetString("InvalidFieldValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 144.
        /// </summary>
        public static string InvalidFirstName {
            get {
                return ResourceManager.GetString("InvalidFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 67.
        /// </summary>
        public static string InvalidGeocodes {
            get {
                return ResourceManager.GetString("InvalidGeocodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 533.
        /// </summary>
        public static string InvalidIATANumber {
            get {
                return ResourceManager.GetString("InvalidIATANumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 145.
        /// </summary>
        public static string InvalidLastName {
            get {
                return ResourceManager.GetString("InvalidLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 640.
        /// </summary>
        public static string InvalidMaxPriceFilter {
            get {
                return ResourceManager.GetString("InvalidMaxPriceFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 157.
        /// </summary>
        public static string InvalidMembershipInformation {
            get {
                return ResourceManager.GetString("InvalidMembershipInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 549.
        /// </summary>
        public static string InvalidMethodOfPayment {
            get {
                return ResourceManager.GetString("InvalidMethodOfPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 639.
        /// </summary>
        public static string InvalidMinPriceFilter {
            get {
                return ResourceManager.GetString("InvalidMinPriceFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 151.
        /// </summary>
        public static string InvalidPhoneInformation {
            get {
                return ResourceManager.GetString("InvalidPhoneInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 461.
        /// </summary>
        public static string InvalidPhoneType {
            get {
                return ResourceManager.GetString("InvalidPhoneType", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 508.
        /// </summary>
        public static string InvalidPickupCriteria {
            get {
                return ResourceManager.GetString("InvalidPickupCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 502.
        /// </summary>
        public static string InvalidPickupDate {
            get {
                return ResourceManager.GetString("InvalidPickupDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 539.
        /// </summary>
        public static string InvalidPickupLocation {
            get {
                return ResourceManager.GetString("InvalidPickupLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 503.
        /// </summary>
        public static string InvalidPickupTimeFormat {
            get {
                return ResourceManager.GetString("InvalidPickupTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 4.
        /// </summary>
        public static string InvalidPosId {
            get {
                return ResourceManager.GetString("InvalidPosId", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 311.
        /// </summary>
        public static string InvalidProductNameInMetadataRequest {
            get {
                return ResourceManager.GetString("InvalidProductNameInMetadataRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 98.
        /// </summary>
        public static string InvalidRadius {
            get {
                return ResourceManager.GetString("InvalidRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 650.
        /// </summary>
        public static string InvalidRadiusForCarSearch {
            get {
                return ResourceManager.GetString("InvalidRadiusForCarSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 532.
        /// </summary>
        public static string InvalidRateCode {
            get {
                return ResourceManager.GetString("InvalidRateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 99.
        /// </summary>
        public static string InvalidRateIdFormat {
            get {
                return ResourceManager.GetString("InvalidRateIdFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 585.
        /// </summary>
        public static string InvalidRentalDuration {
            get {
                return ResourceManager.GetString("InvalidRentalDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 607.
        /// </summary>
        public static string InvalidRentalId {
            get {
                return ResourceManager.GetString("InvalidRentalId", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 546.
        /// </summary>
        public static string InvalidRentalLocation {
            get {
                return ResourceManager.GetString("InvalidRentalLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 5.
        /// </summary>
        public static string InvalidRequest {
            get {
                return ResourceManager.GetString("InvalidRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 575.
        /// </summary>
        public static string InvalidReservation {
            get {
                return ResourceManager.GetString("InvalidReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 232.
        /// </summary>
        public static string InvalidSearchDate {
            get {
                return ResourceManager.GetString("InvalidSearchDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 649.
        /// </summary>
        public static string InvalidSearchLocationFormat {
            get {
                return ResourceManager.GetString("InvalidSearchLocationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 535.
        /// </summary>
        public static string InvalidSearchLocations {
            get {
                return ResourceManager.GetString("InvalidSearchLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 1.
        /// </summary>
        public static string InvalidSessionId {
            get {
                return ResourceManager.GetString("InvalidSessionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 250.
        /// </summary>
        public static string InvalidSupplierId {
            get {
                return ResourceManager.GetString("InvalidSupplierId", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 113.
        /// </summary>
        public static string InvalidSupplierIdInSupplierSpecificOptions {
            get {
                return ResourceManager.GetString("InvalidSupplierIdInSupplierSpecificOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 186.
        /// </summary>
        public static string InvalidSupplierResponse {
            get {
                return ResourceManager.GetString("InvalidSupplierResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 488.
        /// </summary>
        public static string InvalidTimeFormat {
            get {
                return ResourceManager.GetString("InvalidTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 460.
        /// </summary>
        public static string InvalidTitleInName {
            get {
                return ResourceManager.GetString("InvalidTitleInName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 577.
        /// </summary>
        public static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 233.
        /// </summary>
        public static string InvalidValueInRequest {
            get {
                return ResourceManager.GetString("InvalidValueInRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 631.
        /// </summary>
        public static string InvalidVehicleCategory {
            get {
                return ResourceManager.GetString("InvalidVehicleCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 513.
        /// </summary>
        public static string InvalidVehicleCategoryFilter {
            get {
                return ResourceManager.GetString("InvalidVehicleCategoryFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 630.
        /// </summary>
        public static string InvalidVehicleType {
            get {
                return ResourceManager.GetString("InvalidVehicleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 512.
        /// </summary>
        public static string InvalidVehicleTypeFilter {
            get {
                return ResourceManager.GetString("InvalidVehicleTypeFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 514.
        /// </summary>
        public static string InvalidVendorFilter {
            get {
                return ResourceManager.GetString("InvalidVendorFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 548.
        /// </summary>
        public static string InvalidVendorName {
            get {
                return ResourceManager.GetString("InvalidVendorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 591.
        /// </summary>
        public static string InvalidVendorSpecificOptions {
            get {
                return ResourceManager.GetString("InvalidVendorSpecificOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 39.
        /// </summary>
        public static string InvalidVersion {
            get {
                return ResourceManager.GetString("InvalidVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 483.
        /// </summary>
        public static string IpAddressMissingOrInvalid {
            get {
                return ResourceManager.GetString("IpAddressMissingOrInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 143.
        /// </summary>
        public static string LastNameLengthExceeded {
            get {
                return ResourceManager.GetString("LastNameLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 496.
        /// </summary>
        public static string LookUpFailed {
            get {
                return ResourceManager.GetString("LookUpFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 555.
        /// </summary>
        public static string MatchingVehicleNotFound {
            get {
                return ResourceManager.GetString("MatchingVehicleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 69.
        /// </summary>
        public static string Metadata {
            get {
                return ResourceManager.GetString("Metadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 641.
        /// </summary>
        public static string MinPriceGreaterThanMax {
            get {
                return ResourceManager.GetString("MinPriceGreaterThanMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 648.
        /// </summary>
        public static string MissingAddressCity {
            get {
                return ResourceManager.GetString("MissingAddressCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 646.
        /// </summary>
        public static string MissingAddressCountryCode {
            get {
                return ResourceManager.GetString("MissingAddressCountryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 153.
        /// </summary>
        public static string MissingAddressLine {
            get {
                return ResourceManager.GetString("MissingAddressLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 647.
        /// </summary>
        public static string MissingAddressLine1 {
            get {
                return ResourceManager.GetString("MissingAddressLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 645.
        /// </summary>
        public static string MissingAddressPostalCode {
            get {
                return ResourceManager.GetString("MissingAddressPostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 489.
        /// </summary>
        public static string MissingAirportCode {
            get {
                return ResourceManager.GetString("MissingAirportCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 587.
        /// </summary>
        public static string MissingAllowedVehicleCategoriesInFilter {
            get {
                return ResourceManager.GetString("MissingAllowedVehicleCategoriesInFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 588.
        /// </summary>
        public static string MissingAllowedVehicleTypesInFilter {
            get {
                return ResourceManager.GetString("MissingAllowedVehicleTypesInFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 168.
        /// </summary>
        public static string MissingBillingAddressCity {
            get {
                return ResourceManager.GetString("MissingBillingAddressCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 329.
        /// </summary>
        public static string MissingBillingAddressCityName {
            get {
                return ResourceManager.GetString("MissingBillingAddressCityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 169.
        /// </summary>
        public static string MissingBillingAddressCountryCode {
            get {
                return ResourceManager.GetString("MissingBillingAddressCountryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 167.
        /// </summary>
        public static string MissingBillingAddressLine1 {
            get {
                return ResourceManager.GetString("MissingBillingAddressLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 170.
        /// </summary>
        public static string MissingBillingAddressPostalCode {
            get {
                return ResourceManager.GetString("MissingBillingAddressPostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 330.
        /// </summary>
        public static string MissingBillingAddressStateCode {
            get {
                return ResourceManager.GetString("MissingBillingAddressStateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 147.
        /// </summary>
        public static string MissingBookingContactNameInformation {
            get {
                return ResourceManager.GetString("MissingBookingContactNameInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 456.
        /// </summary>
        public static string MissingBookingContactPhoneDetails {
            get {
                return ResourceManager.GetString("MissingBookingContactPhoneDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 455.
        /// </summary>
        public static string MissingBookingContactPhoneNumber {
            get {
                return ResourceManager.GetString("MissingBookingContactPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 154.
        /// </summary>
        public static string MissingCityInformation {
            get {
                return ResourceManager.GetString("MissingCityInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 127.
        /// </summary>
        public static string MissingConnectorMetadata {
            get {
                return ResourceManager.GetString("MissingConnectorMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 148.
        /// </summary>
        public static string MissingContactFirstName {
            get {
                return ResourceManager.GetString("MissingContactFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 149.
        /// </summary>
        public static string MissingContactLastName {
            get {
                return ResourceManager.GetString("MissingContactLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 155.
        /// </summary>
        public static string MissingCountryCode {
            get {
                return ResourceManager.GetString("MissingCountryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 165.
        /// </summary>
        public static string MissingCreditCardBillingAddress {
            get {
                return ResourceManager.GetString("MissingCreditCardBillingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 164.
        /// </summary>
        public static string MissingCreditCardCvv {
            get {
                return ResourceManager.GetString("MissingCreditCardCvv", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 162.
        /// </summary>
        public static string MissingCreditCardExpiryDate {
            get {
                return ResourceManager.GetString("MissingCreditCardExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 481.
        /// </summary>
        public static string MissingCreditCardIssuedBy {
            get {
                return ResourceManager.GetString("MissingCreditCardIssuedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 160.
        /// </summary>
        public static string MissingCreditCardNumber {
            get {
                return ResourceManager.GetString("MissingCreditCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 177.
        /// </summary>
        public static string MissingCreditCardStateDetails {
            get {
                return ResourceManager.GetString("MissingCreditCardStateDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 327.
        /// </summary>
        public static string MissingCriteria {
            get {
                return ResourceManager.GetString("MissingCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 283.
        /// </summary>
        public static string MissingCurrency {
            get {
                return ResourceManager.GetString("MissingCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 272.
        /// </summary>
        public static string MissingCustomerInformationInBooking {
            get {
                return ResourceManager.GetString("MissingCustomerInformationInBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 206.
        /// </summary>
        public static string MissingCustomerName {
            get {
                return ResourceManager.GetString("MissingCustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 280.
        /// </summary>
        public static string MissingDateOfBirth {
            get {
                return ResourceManager.GetString("MissingDateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 199.
        /// </summary>
        public static string MissingDetailsInCancellation {
            get {
                return ResourceManager.GetString("MissingDetailsInCancellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 589.
        /// </summary>
        public static string MissingDisAllowedVehicleCategoriesInFilter {
            get {
                return ResourceManager.GetString("MissingDisAllowedVehicleCategoriesInFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 590.
        /// </summary>
        public static string MissingDisAllowedVehicleTypesInFilter {
            get {
                return ResourceManager.GetString("MissingDisAllowedVehicleTypesInFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 586.
        /// </summary>
        public static string MissingDiscountCodes {
            get {
                return ResourceManager.GetString("MissingDiscountCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 627.
        /// </summary>
        public static string MissingDoorCount {
            get {
                return ResourceManager.GetString("MissingDoorCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 511.
        /// </summary>
        public static string MissingDriverAge {
            get {
                return ResourceManager.GetString("MissingDriverAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 510.
        /// </summary>
        public static string MissingDriverInfo {
            get {
                return ResourceManager.GetString("MissingDriverInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 582.
        /// </summary>
        public static string MissingDriverNationality {
            get {
                return ResourceManager.GetString("MissingDriverNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 504.
        /// </summary>
        public static string MissingDropoffAirportOrRentalLocationCode {
            get {
                return ResourceManager.GetString("MissingDropoffAirportOrRentalLocationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 505.
        /// </summary>
        public static string MissingDropoffDate {
            get {
                return ResourceManager.GetString("MissingDropoffDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 499.
        /// </summary>
        public static string MissingDropoffLocation {
            get {
                return ResourceManager.GetString("MissingDropoffLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 633.
        /// </summary>
        public static string MissingDropoffRentalLocationCode {
            get {
                return ResourceManager.GetString("MissingDropoffRentalLocationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 156.
        /// </summary>
        public static string MissingEmailInformation {
            get {
                return ResourceManager.GetString("MissingEmailInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 519.
        /// </summary>
        public static string MissingExternalServiceConfiguration {
            get {
                return ResourceManager.GetString("MissingExternalServiceConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 598.
        /// </summary>
        public static string MissingField {
            get {
                return ResourceManager.GetString("MissingField", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 274.
        /// </summary>
        public static string MissingLocationCode {
            get {
                return ResourceManager.GetString("MissingLocationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 275.
        /// </summary>
        public static string MissingLocationName {
            get {
                return ResourceManager.GetString("MissingLocationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 161.
        /// </summary>
        public static string MissingNameOnCreditCard {
            get {
                return ResourceManager.GetString("MissingNameOnCreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 279.
        /// </summary>
        public static string MissingNationality {
            get {
                return ResourceManager.GetString("MissingNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 327.
        /// </summary>
        public static string MissingPaymentType {
            get {
                return ResourceManager.GetString("MissingPaymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 500.
        /// </summary>
        public static string MissingPickupAirportOrRentalLocationCode {
            get {
                return ResourceManager.GetString("MissingPickupAirportOrRentalLocationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 501.
        /// </summary>
        public static string MissingPickupDate {
            get {
                return ResourceManager.GetString("MissingPickupDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 498.
        /// </summary>
        public static string MissingPickupLocation {
            get {
                return ResourceManager.GetString("MissingPickupLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 632.
        /// </summary>
        public static string MissingPickupRentalLocationCode {
            get {
                return ResourceManager.GetString("MissingPickupRentalLocationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 531.
        /// </summary>
        public static string MissingRateCode {
            get {
                return ResourceManager.GetString("MissingRateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 108.
        /// </summary>
        public static string MissingRateIds {
            get {
                return ResourceManager.GetString("MissingRateIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 77.
        /// </summary>
        public static string MissingRateReferenceId {
            get {
                return ResourceManager.GetString("MissingRateReferenceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 606.
        /// </summary>
        public static string MissingRentalId {
            get {
                return ResourceManager.GetString("MissingRentalId", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 583.
        /// </summary>
        public static string MissingRentalLocationId {
            get {
                return ResourceManager.GetString("MissingRentalLocationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 75.
        /// </summary>
        public static string MissingRoomRate {
            get {
                return ResourceManager.GetString("MissingRoomRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 8.
        /// </summary>
        public static string MissingSessionId {
            get {
                return ResourceManager.GetString("MissingSessionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 276.
        /// </summary>
        public static string MissingStateInformation {
            get {
                return ResourceManager.GetString("MissingStateInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 22.
        /// </summary>
        public static string MissingSupplierConfiguration {
            get {
                return ResourceManager.GetString("MissingSupplierConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 21.
        /// </summary>
        public static string MissingSupplierConfigurations {
            get {
                return ResourceManager.GetString("MissingSupplierConfigurations", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 18.
        /// </summary>
        public static string MissingSupplierDetails {
            get {
                return ResourceManager.GetString("MissingSupplierDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 19.
        /// </summary>
        public static string MissingSupplierId {
            get {
                return ResourceManager.GetString("MissingSupplierId", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 20.
        /// </summary>
        public static string MissingSupplierName {
            get {
                return ResourceManager.GetString("MissingSupplierName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 309.
        /// </summary>
        public static string MissingTenantConfigurations {
            get {
                return ResourceManager.GetString("MissingTenantConfigurations", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 251.
        /// </summary>
        public static string MissingTenantId {
            get {
                return ResourceManager.GetString("MissingTenantId", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 273.
        /// </summary>
        public static string MissingTitleInName {
            get {
                return ResourceManager.GetString("MissingTitleInName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 578.
        /// </summary>
        public static string MissingVehicleCategory {
            get {
                return ResourceManager.GetString("MissingVehicleCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 528.
        /// </summary>
        public static string MissingVehicleDetails {
            get {
                return ResourceManager.GetString("MissingVehicleDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 529.
        /// </summary>
        public static string MissingVehicleSippCode {
            get {
                return ResourceManager.GetString("MissingVehicleSippCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 580.
        /// </summary>
        public static string MissingVehicleTransmission {
            get {
                return ResourceManager.GetString("MissingVehicleTransmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 579.
        /// </summary>
        public static string MissingVehicleType {
            get {
                return ResourceManager.GetString("MissingVehicleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 527.
        /// </summary>
        public static string MissingVendorCode {
            get {
                return ResourceManager.GetString("MissingVendorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 573.
        /// </summary>
        public static string ModelNotAvailable {
            get {
                return ResourceManager.GetString("ModelNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 565.
        /// </summary>
        public static string ModifiedCreditCard {
            get {
                return ResourceManager.GetString("ModifiedCreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 628.
        /// </summary>
        public static string MultiFormOfPaymentNotAllowed {
            get {
                return ResourceManager.GetString("MultiFormOfPaymentNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 625.
        /// </summary>
        public static string NoBookingFoundForCancellation {
            get {
                return ResourceManager.GetString("NoBookingFoundForCancellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 482.
        /// </summary>
        public static string NonCancellableBooking {
            get {
                return ResourceManager.GetString("NonCancellableBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 538.
        /// </summary>
        public static string NoRentalLocationsForGivenCriteria {
            get {
                return ResourceManager.GetString("NoRentalLocationsForGivenCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 13.
        /// </summary>
        public static string NoResultsForSearchCriteria {
            get {
                return ResourceManager.GetString("NoResultsForSearchCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 252.
        /// </summary>
        public static string NoResultsOrAllResultsFilteredOut {
            get {
                return ResourceManager.GetString("NoResultsOrAllResultsFilteredOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 495.
        /// </summary>
        public static string NoSupportForOnlineCancellation {
            get {
                return ResourceManager.GetString("NoSupportForOnlineCancellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 609.
        /// </summary>
        public static string OneWayRentalNotPermitted {
            get {
                return ResourceManager.GetString("OneWayRentalNotPermitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 566.
        /// </summary>
        public static string PackageUnavailable {
            get {
                return ResourceManager.GetString("PackageUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 70.
        /// </summary>
        public static string ParsingFailure {
            get {
                return ResourceManager.GetString("ParsingFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 613.
        /// </summary>
        public static string PhoneCancellation {
            get {
                return ResourceManager.GetString("PhoneCancellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 202.
        /// </summary>
        public static string PricesChanged {
            get {
                return ResourceManager.GetString("PricesChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 525.
        /// </summary>
        public static string RateLimitExceeded {
            get {
                return ResourceManager.GetString("RateLimitExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 558.
        /// </summary>
        public static string RateNotAvailble {
            get {
                return ResourceManager.GetString("RateNotAvailble", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 571.
        /// </summary>
        public static string RentalIncludeWeekday {
            get {
                return ResourceManager.GetString("RentalIncludeWeekday", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 570.
        /// </summary>
        public static string RentalIncludeWeekend {
            get {
                return ResourceManager.GetString("RentalIncludeWeekend", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 562.
        /// </summary>
        public static string RentalPeriodLimitExceeds {
            get {
                return ResourceManager.GetString("RentalPeriodLimitExceeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 617.
        /// </summary>
        public static string RentalTermsNotAvailable {
            get {
                return ResourceManager.GetString("RentalTermsNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 7.
        /// </summary>
        public static string RequestNotFound {
            get {
                return ResourceManager.GetString("RequestNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 52.
        /// </summary>
        public static string RequestProcessingError {
            get {
                return ResourceManager.GetString("RequestProcessingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 618.
        /// </summary>
        public static string ReservationCancelled {
            get {
                return ResourceManager.GetString("ReservationCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 619.
        /// </summary>
        public static string ReservationExists {
            get {
                return ResourceManager.GetString("ReservationExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 553.
        /// </summary>
        public static string ReservationFailed {
            get {
                return ResourceManager.GetString("ReservationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 552.
        /// </summary>
        public static string RetrieveReservationFailed {
            get {
                return ResourceManager.GetString("RetrieveReservationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 73.
        /// </summary>
        public static string ServiceCommunication {
            get {
                return ResourceManager.GetString("ServiceCommunication", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 58.
        /// </summary>
        public static string SessionStoreRead {
            get {
                return ResourceManager.GetString("SessionStoreRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 59.
        /// </summary>
        public static string SessionStoreWrite {
            get {
                return ResourceManager.GetString("SessionStoreWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 204.
        /// </summary>
        public static string StateNotFound {
            get {
                return ResourceManager.GetString("StateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 561.
        /// </summary>
        public static string StationClosed {
            get {
                return ResourceManager.GetString("StationClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 33.
        /// </summary>
        public static string Supplier {
            get {
                return ResourceManager.GetString("Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 105.
        /// </summary>
        public static string SupplierCommunication {
            get {
                return ResourceManager.GetString("SupplierCommunication", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 125.
        /// </summary>
        public static string SupplierConfigurationNotAvailable {
            get {
                return ResourceManager.GetString("SupplierConfigurationNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 484.
        /// </summary>
        public static string SupplierDisabled {
            get {
                return ResourceManager.GetString("SupplierDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 324.
        /// </summary>
        public static string SupplierException {
            get {
                return ResourceManager.GetString("SupplierException", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 14.
        /// </summary>
        public static string SupplierServerDown {
            get {
                return ResourceManager.GetString("SupplierServerDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 15.
        /// </summary>
        public static string SupplierSystem {
            get {
                return ResourceManager.GetString("SupplierSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 180.
        /// </summary>
        public static string SupplierValidation {
            get {
                return ResourceManager.GetString("SupplierValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 6.
        /// </summary>
        public static string System {
            get {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 195.
        /// </summary>
        public static string TenantConfigurationRead {
            get {
                return ResourceManager.GetString("TenantConfigurationRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 115.
        /// </summary>
        public static string TenantNotFound {
            get {
                return ResourceManager.GetString("TenantNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 32.
        /// </summary>
        public static string TimeOut {
            get {
                return ResourceManager.GetString("TimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 314.
        /// </summary>
        public static string TranslationMissing {
            get {
                return ResourceManager.GetString("TranslationMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 610.
        /// </summary>
        public static string TravelBetweenStationsNotPermitted {
            get {
                return ResourceManager.GetString("TravelBetweenStationsNotPermitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 559.
        /// </summary>
        public static string UnableToTransact {
            get {
                return ResourceManager.GetString("UnableToTransact", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 362.
        /// </summary>
        public static string UnexpectedSystemException {
            get {
                return ResourceManager.GetString("UnexpectedSystemException", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 12.
        /// </summary>
        public static string UnMappedSupplier {
            get {
                return ResourceManager.GetString("UnMappedSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 131.
        /// </summary>
        public static string UnSupportedCulture {
            get {
                return ResourceManager.GetString("UnSupportedCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 141.
        /// </summary>
        public static string UnSupportedLoyaltyMembership {
            get {
                return ResourceManager.GetString("UnSupportedLoyaltyMembership", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 132.
        /// </summary>
        public static string UnSupportedRateTypes {
            get {
                return ResourceManager.GetString("UnSupportedRateTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 139.
        /// </summary>
        public static string UnSupportedSpecialRequest {
            get {
                return ResourceManager.GetString("UnSupportedSpecialRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 55.
        /// </summary>
        public static string ValidationFailure {
            get {
                return ResourceManager.GetString("ValidationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 557.
        /// </summary>
        public static string VehicleClassNotSupported {
            get {
                return ResourceManager.GetString("VehicleClassNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 556.
        /// </summary>
        public static string VehicleTypeNotSupported {
            get {
                return ResourceManager.GetString("VehicleTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 312.
        /// </summary>
        public static string WrongConnectorIdentifier {
            get {
                return ResourceManager.GetString("WrongConnectorIdentifier", resourceCulture);
            }
        }
    }
}
